sudo: required

language: java

services:
  - docker

after_success:
  - docker-compose up --abort-on-container-exit #stop all services once one container has finished.

# This will gracefully exit the MySQL container when the main application exits in Travis CI